version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: raw data from big query 
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales for greenweez / pdt_id as products_id / PK is date_date + products_id
        columns: 
        - name: (orders_id||'_'||pdt_id)
          tests: 
            - unique
        freshness: 
           warn_after:
            count: 90
            period: day
        loaded_at_field: CAST(date_date AS TIMESTAMP)
      - name: product
        identifier: raw_gz_product
        description: different products from greenweez / purchse_price as purchase_price
        columns: 
        - name: products_id
          tests: 
            - unique
            - not_null  
      - name: ship
        identifier: raw_gz_ship
        description: different shippings from greenweez / PK is oreder id? 
        columns: 
        - name: orders_id
          tests: 
            - unique
            - not_null  
        
